### ISSUE TITLE
Бонусные задания по предмету .NET Core

### ISSUE THREAD

**Issue by nurgi17** [nurgi17/SWD6.NET#2]
@nightBaker 

Здравствуйте агай, я Усен Н. с группы CSSE-1601(21776), хотел попросить бонусные задания для повышения оценки по предмету .NET Core. Я обговаривал этот вопрос с вами, вы сказали что обсудите это с своим коллегой и сказали написать по этому.

**Comment by nightBaker** [comment]
Здравствуй. Мы обговорили с Кайратом, решили что заданий не будет
